---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dwybourn/SpringCloudConfigDemoValues
          search-paths:
            - 'station*'